---
- name: Include variables
  include_vars: "{{inventory_dir}}/../vars/main.yml"

- name: Allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Allow all access from other nodes to this host
  community.general.ufw:
    rule: allow
    src: '{{ item.cidr }}'
    port: '{{ item.port }}'
    proto: '{{ item.protocol }}'
  loop: '{{ ufw.allow }}'
  become: true

- name: deny  access from other nodes to this host
  community.general.ufw:
    rule: deny
    src: '{{ item.cidr }}'
    port: '{{ item.port }}'
    proto: '{{ item.protocol }}'
  loop: '{{ ufw.deny }}'
  become: true

- name: Deny all access to port 443
  community.general.ufw:
    rule: deny
    port: '443'
    proto: tcp
  become: true

- name: Allow everything and disable UFW
  community.general.ufw:
    state: enabled
  become: true
