---
  - name: Main playbook that gets deployed to all new linux bare metal.
    hosts: all
    gather_facts: false
    roles:
        - role: common/bastion_ssh_only
          when: inventory_hostname in groups["baremetal_nodes"]
        - common/update_apt
        - common/msmtp
        - common/chrony
        - role: common/docker
          tags:
            - docker
        - common/vimrc
        - common/traefik
        - role: common/dockerufw
          when: inventory_hostname in groups["baremetal_nodes"]
        - role: common/ufw
          when: inventory_hostname in groups["baremetal_nodes"]
        - common/upgrades
        - role: common/diskspace-crontab
          tags:
            - diskspace-crontab
        - common/performance
