---
  - name: Main playbook that gets deployed to all new linux bare metal.
    hosts: all
    gather_facts: false
    roles:
        - common/bastion_ssh_only
        - common/update_apt
        - common/msmtp
        - common/chrony
        - role: common/docker
          tags:
            - docker
        - common/vimrc
        - common/traefik
        - common/dockerufw
        - common/ufw
        - common/upgrades
        - role: common/diskspace-crontab
          tags:
            - diskspace-crontab
        - common/performance
