---
- name: Main playbook that gets deployed to all new linux bare metal.
  hosts: all
  gather_facts: false
  roles:
    - base/update_apt
    - role: base/bastion_ssh_only
      when: inventory_hostname in groups["baremetal_nodes"]
    - base/msmtp
    - role: base/docker
      tags:
        - docker
    - base/vimrc
    - base/traefik
    - role: base/dockerufw
      when: inventory_hostname in groups["baremetal_nodes"]
    - role: base/ufw
      when: inventory_hostname in groups["baremetal_nodes"]
    - base/upgrades
    - role: base/diskspace-crontab
      tags:
        - diskspace-crontab
    - base/performance
