---
- name: Install common helper packages
  apt:
    name:
    - htop
    - bc
    - chrony
    - jq
    - smartmontools
    - needrestart
    - ufw
    - cron
    - git
    - dbus
    update_cache: yes
    cache_valid_time: 86400
  become: true

- name: Start service dbus, if not started
  ansible.builtin.service:
    name: dbus.socket
    state: started
  become: true
