---
- name: clone repo
  ansible.builtin.git:
    repo: https://github.com/eth-educators/eth-docker.git
    dest: "~/{{clone_dir}}"
    version: rpc-nodes
- name: Create .env file
  ansible.builtin.copy:
    src: "~/{{clone_dir}}/default.env"
    dest: "~/{{clone_dir}}/.env"
    remote_src: yes
- name: set  COMPOSE_FILE 
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^COMPOSE_FILE='
    line: COMPOSE_FILE={{DEPLOY_COMPOSE_FILE}}
  when: DEPLOY_COMPOSE_FILE is defined
- name: set  NETWORK 
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^NETWORK='
    line: NETWORK={{NETWORK}}
  when: NETWORK is defined
- name: set  EC_NETWORK 
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^EC_NETWORK='
    line: EC_NETWORK={{EC_NETWORK}}
  when: EC_NETWORK is defined
- name: set  LH_PEER_COUNT
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^LH_PEER_COUNT='
    line: LH_PEER_COUNT={{LH_PEER_COUNT}}
  when: LH_PEER_COUNT is defined
- name: set  PRYSM_PEER_COUNT
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^PRYSM_PEER_COUNT='
    line: PRYSM_PEER_COUNT={{PRYSM_PEER_COUNT}}
  when: PRYSM_PEER_COUNT is defined
- name: set  TEKU_PEER_COUNT
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^TEKU_PEER_COUNT='
    line: TEKU_PEER_COUNT={{TEKU_PEER_COUNT}}
  when: TEKU_PEER_COUNT is defined
- name: set  NIM_PEER_COUNT
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^NIM_PEER_COUNT='
    line: NIM_PEER_COUNT={{NIM_PEER_COUNT}}
  when: NIM_PEER_COUNT is defined
- name: set  DOMAIN 
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^DOMAIN='
    line: DOMAIN={{DOMAIN}}
  when: DOMAIN is defined
- name: set  GRAFANA_HOST
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^GRAFANA_HOST='
    line: GRAFANA_HOST={{GRAFANA_HOST}}
  when: GRAFANA_HOST is defined
- name: set  EC_HOST
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^EC_HOST='
    line: EC_HOST={{EC_HOST}}
  when: EC_HOST is defined
- name: set  EC_LB
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^EC_LB='
    line: EC_LB={{EC_LB}}
  when: EC_LB is defined

- name: set  EC_WS_HOST 
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^EC_WS_HOST='
    line: EC_WS_HOST={{EC_WS_HOST}}
  when: EC_WS_HOST is defined
- name: set  EC_WS_LB
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^EC_WS_LB='
    line: EC_WS_LB={{EC_WS_LB}}
  when: EC_WS_LB is defined

- name: set  CC_HOST
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^CC_HOST='
    line: CC_HOST={{CC_HOST}}
  when: CC_HOST is defined

- name: set  CC_LB
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^CC_LB='
    line: CC_LB={{CC_LB}}
  when: CC_LB is defined

- name: set  TEKU_RAPID_SYNC
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^TEKU_RAPID_SYNC='
    line: TEKU_RAPID_SYNC={{TEKU_RAPID_SYNC}}
  when: TEKU_RAPID_SYNC is defined

- name: set  LH_RAPID_SYNC
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^LH_RAPID_SYNC='
    line: LH_RAPID_SYNC={{LH_RAPID_SYNC}}
  when: LH_RAPID_SYNC is defined

- name: set  NIMBUS_RAPID_SYNC
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^NIMBUS_RAPID_SYNC='
    line: NIMBUS_RAPID_SYNC={{NIMBUS_RAPID_SYNC}}
  when: NIMBUS_RAPID_SYNC is defined

- name: set  LS_RAPID_SYNC 
  ansible.builtin.lineinfile:
    path: "~/{{clone_dir}}/.env"
    regexp: '^LS_RAPID_SYNC='
    line: LS_RAPID_SYNC={{LS_RAPID_SYNC}}
  when: LS_RAPID_SYNC is defined

- name: deploy node
  ansible.builtin.shell: ./ethd up
  args:
    chdir: ~/{{clone_dir}}
