---
- name: clone repo
  ansible.builtin.git:
    repo: https://github.com/eth-educators/eth-docker.git
    dest: "~/{{clone_dir}}"
    version: main

- name: Check if .env file exists
  ansible.builtin.stat:
    path: "~/{{clone_dir}}/.env"
  register: env_file_status

- name: Create .env file
  ansible.builtin.copy:
    src: "~/{{clone_dir}}/default.env"
    dest: "~/{{clone_dir}}/.env"
    remote_src: yes
  when: not env_file_status.stat.exists

- name: set variables
  ansible.builtin.lineinfile:
    path: "~/{{ clone_dir }}/.env"
    regexp: '^{{ item.key }}='
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ env_variables }}"
  when: env_variables is defined

- name: set group variables
  ansible.builtin.lineinfile:
    path: "~/{{ clone_dir }}/.env"
    regexp: '^{{ item.key }}='
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ group_env_variables }}"
  when: group_env_variables is defined

- name: Deploy custom-prom.yml file
  ansible.builtin.template:
    src: custom-prom.yml.j2
    dest: ~/{{ clone_dir }}/prometheus/custom-prom.yml
  when: prom_environment is defined

- name: start node
  ansible.builtin.shell: ./ethd up
  args:
    chdir: ~/{{clone_dir}}
