---
- name: Insert/Update new rules  to /etc/ufw/after.rules
  blockinfile:
    path: /etc/ufw/after.rules
    block: |
      *filter
      :ufw-user-input - [0:0]
      :DOCKER-USER - [0:0]

      # ufw in front of docker while allowing all inter-container traffic

      -A DOCKER-USER -j RETURN -s 10.0.0.0/8
      -A DOCKER-USER -j RETURN -s 172.16.0.0/12
      -A DOCKER-USER -j RETURN -s 192.168.0.0/16

      -A DOCKER-USER -j ufw-user-input
      -A DOCKER-USER -j RETURN

      COMMIT
  become: true

- name: Insert/Update /etc/ufw/before.init
  blockinfile:
    path: /etc/ufw/before.init
    #marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: '^stop\)'
    mode: '750'
    block: |
      #Required
          iptables -F DOCKER-USER || true
          iptables -A DOCKER-USER -j RETURN || true
          iptables -X ufw-user-input || true
  become: true

- name: Reload UFW
  community.general.ufw:
    state: reloaded
  become: true
