---
# ---
#   - name: Playbook
#     hosts: localhost
#     # become: yes
#     # become_user: root
#     tasks:
- name: clone repo
  ansible.builtin.git:
    repo: https://github.com/eth-educators/eth-docker.git
    dest: ~/traefik
- name: Create .env file
  ansible.builtin.copy:
    src: ~/traefik/default.env
    dest: ~/traefik/.env
    remote_src: yes
- name: set  COMPOSE_FILE to traefik-cf.yml:traefik-shared.yml
  ansible.builtin.lineinfile:
    path: ~/traefik/.env
    regexp: '^COMPOSE_FILE='
    line: COMPOSE_FILE=traefik-cf.yml:traefik-shared.yml
- name: set DOMAIN to   cryptomanufaktur.net
  ansible.builtin.lineinfile:
    path: ~/traefik/.env
    regexp: '^DOMAIN='
    line: DOMAIN=cryptomanufaktur.net
- name: set DDNS_PROXY to   false
  ansible.builtin.lineinfile:
    path: ~/traefik/.env
    regexp: '^DDNS_PROXY='
    line: DDNS_PROXY=false
- name: Get hostname
  shell: hostname
  register: result
- name: Print the var
  debug:
    var: result
- name: set DDNS_SUBDOMAIN to   hostname
  ansible.builtin.lineinfile:
    path: ~/traefik/.env
    regexp: '^DDNS_SUBDOMAIN='
    line: DDNS_SUBDOMAIN=ssh.{{result.stdout}}
  
- name: set ACME_EMAIL
  ansible.builtin.lineinfile:
    path: ~/traefik/.env
    regexp: '^ACME_EMAIL='
    line: ACME_EMAIL={{acme_email}}

- name: set CF_EMAIL
  ansible.builtin.lineinfile:
    path: ~/traefik/.env
    regexp: '^CF_EMAIL='
    line: CF_EMAIL={{cf_email}}

- name: set CF_API_TOKEN
  ansible.builtin.lineinfile:
    path: ~/traefik/.env
    regexp: '^CF_API_TOKEN='
    line: CF_API_TOKEN={{cf_api_token}}

- name: Install traefik if not exisiting
  ansible.builtin.shell: ./ethd up
  become: true
  args:
    creates: /etc/traefik/success
    chdir: ~/traefik 
