---
- name: Get distribution version
  setup:
    filter: ansible_distribution*
- name: Skip if not Debian 11
  meta: end_host
  when: ansible_distribution != 'Debian' or ansible_distribution_version != '11'
- name: apt clean
  apt:
    clean: yes
  become: yes
- name: Get filesystem facts
  setup:
    filter: ansible_mounts
- name: Fail if free space on / is below 3 GiB
  ansible.builtin.assert:
    that:
      - item.size_available > (3 * 1024 * 1024 * 1024)
    fail_msg: "Free disk space on {{ item.mount }} is below 3 GiB"
  loop: "{{ ansible_mounts }}"
  when: item.mount == "/"
- name: All apt packages up to date
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
- name: apt autoremove
  apt:
    autoremove: yes
  become: yes
- name: apt clean
  apt:
    clean: yes
  become: yes
- name: Switch OS from bullseye to bookworm
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: 'bullseye'
    replace: 'bookworm'
  become: yes
- name: Add non-free-firmware if non-free is in use
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '(.*non-free.*)'
    replace: '\1 non-free-firmware'
  become: yes
- name: Find all 3rd-party repos
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: '*'
    recurse: no
  register: third_party_repos
- name: Switch 3rd-party repos from bullseye to bookworm
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: 'bullseye'
    replace: 'bookworm'
  loop: "{{ third_party_repos.files }}"
  loop_control:
    label: "{{ item.path }}"
  become: yes
- name: Use apt to move to bookworm
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
- name: Get distribution version
  setup:
    filter: ansible_distribution*
- name: Fail if not Debian 12
  assert:
    that:
      - ansible_distribution_version  == '12'
    fail_msg: "Upgrade to Debian 12 failed"
- name: apt autoremove
  apt:
    autoremove: yes
  become: yes
- name: apt clean
  apt:
    clean: yes
  become: yes
- name: Re-enable msmtp apparmor profile
  ansible.builtin.file:
    path: /etc/apparmor.d/disable/usr.bin.msmtp
    state: absent
  become: yes
- name: Restart apparmor service
  ansible.builtin.systemd:
    name: apparmor
    state: restarted
  become: yes
- name: Reboot on bookworm
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: whoami
  become: yes
- name: Pause for 5 minutes to allow node to come back into sync
  pause:
    minutes: 5
