---
# - name: Include variables
#   include_vars: "{{inventory_dir}}/group_vars/main.yml"

- name: Allow all access from other nodes to this host
  community.general.ufw:
    rule: allow
    src: '{{ item.cidr }}'
    port: '{{ item.port }}'
    proto: '{{ item.protocol }}'
    comment: '{{ item.description }}'
  loop: '{{ ufw.allow }}'
  become: true

- name: deny  access from other nodes to this host
  community.general.ufw:
    rule: deny
    src: '{{ item.cidr }}'
    port: '{{ item.port }}'
    proto: '{{ item.protocol }}'
    comment: "Deny access from specific hosts"
  loop: '{{ ufw.deny }}'
  become: true

- name: Deny all access to port 443
  community.general.ufw:
    rule: deny
    port: '443'
    proto: tcp
  become: true

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
  become: true
