---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"
  become: true

- name: Print hostname
  debug:
    msg: "Hostname set to {{ inventory_hostname_short }}"
