traefik_acme_email: acme@example.com
traefik_cf_api_token: "cloudflare_token"
traefik_cf_email: cloudflareemail@example.com

upgrades_UU_CONF: /etc/apt/apt.conf.d/50unattended-upgrades
upgrades_UU_START: /etc/apt/apt.conf.d/20auto-upgrades
upgrades_EMAIL_TO: email@example.com
upgrades_SSMTP_CONF: /etc/ssmtp/ssmtp.conf
upgrades_EMAIL: email@example.com
upgrades_EPW: SMTP_EMAIL_PASSWORD
upgrades_MAILSRV: smtp.gmail.com:587
upgrades_REBOOT_AT: -02:00

ufw:
  allow:
    - cidr: 54.39.105.149/32
      port: 443
      protocol: tcp
    - cidr: 51.81.245.170/32
      port: 443
      protocol: tcp
    - cidr: 135.148.100.24/32
      port: 443
      protocol: tcp
    - cidr: 3.23.168.174/32
      port: 443
      protocol: tcp
    - cidr: 18.221.182.50/32
      port: 443
      protocol: tcp
    - cidr: 3.140.37.229/32
      port: 443
      protocol: tcp
    - cidr: 18.219.222.13/32
      port: 443
      protocol: tcp
    - cidr: 3.142.203.190/32
      port: 443
      protocol: tcp
    - cidr: 3.14.174.129/32
      port: 443
      protocol: tcp
  deny:
    - cidr: 0.0.0.0/0
      port: 443
      protocol: tcp
